

// for (let i = 1; i <= 0; i++) {
//     console.log("i =", i)
// }

// let i = 24;
// while (i <= 10) {
//     console.log("Musa Muhammad");
//     i++;
// }

// let i = 2;
// do {
//     console.log("Musa Muhammad");
//     i++;
// } while (i <= 8)

// For-Of Loop
// let str = "Muhammad Musa";

// let size = 0;
// for(let val of str) {
//     console.log("i =", val);
//     size++;
// }

// console.log("string size =", size);

// let student = {
//     name: "Muhammad Musa",
//      age: 20,
//      cgpa: 7.5,
//      ispass: true
// };

// for(let i in student) {
//     console.log("key =", key, "value =", student[key]);
// }


// Practice:
// for(let num = 0; num <= 100; num++) {
//    if(num%2 === 0) {
//     console.log("num =", num);
//    }
// }

// let gnum = 25;
// let unum = prompt("Guess The Number:");
// console.log(unum)

// while (unum != gnum) {
//     unum = prompt("B");
// }

// console.log("A");

// Strings
// let str = "Kinggdom Come: Deliverance";

// console.log(str[4]);

// let obj = {
//     item: "Game Hardrive",
//     name: "Need For Speed Heat",
//     Price: "15,000Rs",
// }

// let output = `The ${obj.item} Name Of Game Is ${obj.name} Price Is ${obj.Price}`
// console.log(output)
// console.log( "The", obj.item,"Name Of Game Is", obj.name, "Price Is", obj.Price) <= Possible To Do Like This

// Template Literals

// let specialGame = `Expedition 33 ${1+2+3}`;
// console.log(typeof specialGame);

// console.log("Unkox\n1890");
// console.log("Unkox\t1890");

// let str = "Unkox1890"
// str.toUpperCase(); ❌

// let str = "Unkox1890"
// let newstr = str.toUpperCase(); //✔️ (Same Goes For toLowerCase btw)

// console.log(str)
// console.log(newstr)

// let str = "12345678";
// console.log(str.slice(1, 5));
 
// let str1 = "Unkox";
// let str2 = "1890";

// let res = "I Am Learning Coding From" + str1 + str2;
// console.log(res)

// let str = "hello"

// console.log(str.replace("lo", "p")); <== Both Can Be Used
// console.log(str.replaceAll("lo", "p"));

// let str = " I HATE JS!!!!";
// str = str.replace("I", "U")
// console.log(str.charAt(0));

let fulname = prompt("Enter Ur Full Name Without Spaces ");

let usrname = "@" + fulname.length;
console.log(fulname);















